### ISSUE TITLE
most recent code not available

### ISSUE THREAD

**Issue by Lx** [Tekki/sql-ledger#1]
The SQL-Ledger [What's New](http://www.sql-ledger.com/cgi-bin/nav.pl?page=misc/whatsnew.html&title=What's%20New) page lists v3.0.5 (May 24, 2013) as the latest release, but the master branch only holds v3.0.3 (June 5, 2012).

**Comment by lkraav** [comment]
Hey, same bump for 3.2.1. Maybe doesn't make sense to open a new issue for this.

**Comment by Tekki** [comment]
I have some issues with the new version. For the moment I don't upgrade.
