### ISSUE TITLE
Documents not attaching to payroll transaction

### ISSUE THREAD

**Issue by gopokyo-colinn** [Tekki/sql-ledger#39]
I have not yet been able to determine the cause, but documents are not attaching to payroll transactions properly.

When I "list documents" I can see the descriptions of the files and that they are attached to the payroll transaction, but folder and filename are empty.  When I click on the document description I am sent to a page where I can modify the folder an filename but not attempt to upload the pdf again

things I will check into:
Files upload have spaces them - issue?

documents are attaching to AP transactions

**Comment by Tekki** [comment]
I must confess I've never used the internal upload function, I always link to external cloud services. But I've tried now and can reproduce this issue.
If we add a document to an existing payroll transaction and then click on the link there is a 'Document not archived!' error.

**Comment by gopokyo-colinn** [comment]
Seems to happen with General Ledger/Journal entries as well.  Did not check for a log entry (I am running on ec2 in a docker image and am actually not sure where to find the log)

**Comment by Tekki** [comment]
These errors are easy to reproduce, you don't have to look for logs.
Do you use my Docker image from Dockerhub or something you built yourself?

**Comment by gopokyo-colinn** [comment]
Yah, using your docker image :)

**Comment by Tekki** [comment]
Nice, I had no idea if anyone is using it. In this case I have to update it too, it's still on version 3.2.7.10.

**Comment by Tekki** [comment]
The Docker image is updated. Attention: `sql-ledger.conf` is no longer an editable file, but configured via environment variables.

**Comment by Tekki** [comment]
Resolved with f6ca4c53 in version 3.2.12.41.
