### ISSUE TITLE
Request support for Indian Numbering System

### ISSUE THREAD

**Issue by suhasagubb** [Tekki/sql-ledger#40]
India follows a different 'Number Format'. Request to support the same.
https://en.wikipedia.org/wiki/Indian_numbering_system

Examples:
1,000.00
10,000.00
1,00,000.00
10,00,000.00
1,00,00,000.00
So on...

**Comment by Tekki** [comment]
I'll take a look at it. That's interesting, never heard of this format before. At the moment we assume groups of 3.

**Comment by Tekki** [comment]
Should be working now. Feel free to reopen this issue if it doesn't.

**Comment by suhasagubbi** [comment]
Thanks, it works as expected now!
