### ISSUE TITLE
Stock Assembly - Check Inventory option is not working

### ISSUE THREAD

**Issue by suhasagubbi** [Tekki/sql-ledger#41]
I have created 1 part and 2 assemblies with following correlation:
```
Assembly1 uses Part1
Assembly2 uses Assembly1
```

Part is purchased by _AP - Vendor Invoice_ and quantity is stocked to inventory.

After this, when I try to `Stock Assembly` by selecting the `Check Inventory` checkbox, no parts/assemblies are displayed, even when parts/assemblies are in sufficient quantity.

cc @Tekki

**Comment by Tekki** [comment]
Neither we nor any of my customers has ever used the assembly module, so I'm probably not the one to answer this question. I'll leave this issue open, maybe I have time to look into it.

**Comment by suhasagubbi** [comment]
Thanks for the update...

**Comment by Tekki** [comment]
I've opened the discussions tab in this repo. If you're still looking for an answer please start a discussion.
