### ISSUE TITLE
Add Assembly - Creates an empty & corrupted assembly entry when Description is not entered

### ISSUE THREAD

**Issue by suhasagubbi** [Tekki/sql-ledger#42]
Steps to reproduce:
1. Go to `Add Assembly`
2. Leave `Description` empty.
3. Define valid `Individual Items (Parts)`
4. Click on `Save` (Refer screenshot-1)
5. Error is shown as in screenshot-2.
6. But Assembly with blank Description is added to list as shown in screenshot-3
7. Further it is not possible to either update this Assembly or delete the assembly.

_Screenshot-1:_
![Screenshot from 2020-06-12 01-54-02](https://user-images.githubusercontent.com/9989095/84436040-6cbe6680-ac50-11ea-9718-61c48a9f5f62.png)

_Screenshot-2:_
![Assembly_Add_1](https://user-images.githubusercontent.com/9989095/84436053-71831a80-ac50-11ea-9036-68ddff012562.PNG)

_Screenshot-3:_
![Assembly_Add_2](https://user-images.githubusercontent.com/9989095/84436050-71831a80-ac50-11ea-87c4-5cf9d9dfaf9d.PNG)

**Comment by Tekki** [comment]
Can I ask you for what reason you create an assembly without description?

**Comment by suhasagubbi** [comment]
It was not intentional, by mistake I added and now unable to delete it or change it.

Also during some other operation, the same part has been duplicated and showing 3 times. Do not know which operation lead to that. Now inventory has gone for a toss and unable to stock assembly.

**Comment by Tekki** [comment]
You can now change or delete items with empty description.

> Also during some other operation, the same part has been duplicated and showing 3 times.

Items don't just duplicate by themselves, this is probably a user error. One way to accidentally create duplicates is to create a new object, press the `back` button in the browser and click on `save` again. Be careful, like every other ERP solution this software is not self-explanatory. Make backups regularly, especially before you start with big changes.

**Comment by suhasagubbi** [comment]
Thanks. For now, change / delete items with empty description should be good enough.

Will keep a check on the other part and use carefully as suggested.
