### ISSUE TITLE
customer problem after upgrade to 3.2.9.16

### ISSUE THREAD

**Issue by pjaouen** [Tekki/sql-ledger#43]
DBD::Pg::st execute failed: ERREUR: la colonne bk.qriban n'existe pas
LINE 8: bk.name AS bankname, bk.iban, bk.qriban, bk....
^
HINT: Peut-être que vous souhaitiez référencer la colonne « bk.iban ». at SL/CT.pm line 63.
Error!
SELECT ct.*,
ad.id AS addressid, ad.address1, ad.address2, ad.city,
ad.state, ad.zipcode, ad.country,
b.description AS business, b.id AS business_id, s.*,
e.name AS employee, e.id AS employee_id,
g.pricegroup, g.id AS pricegroup_id,
m.description AS paymentmethod, m.id AS paymentmethod_id,
bk.name AS bankname, bk.iban, bk.qriban, bk.bic,
bk.membernumber, bk.clearingnumber,
ad1.address1 AS bankaddress1,
ad1.address2 AS bankaddress2,
ad1.city AS bankcity,
ad1.state AS bankstate,
ad1.zipcode AS bankzipcode,
ad1.country AS bankcountry,
ct.curr
FROM customer ct
JOIN address ad ON (ct.id = ad.trans_id)
LEFT JOIN business b ON (ct.business_id = b.id)
LEFT JOIN shipto s ON (ct.id = s.trans_id)
LEFT JOIN employee e ON (ct.employee_id = e.id)
LEFT JOIN pricegroup g ON (g.id = ct.pricegroup_id)
LEFT JOIN paymentmethod m ON (m.id = ct.paymentmethod_id)
LEFT JOIN bank bk ON (bk.id = ct.id)
LEFT JOIN address ad1 ON (bk.address_id = ad1.id)
WHERE ct.id = 23094
ERREUR: la colonne bk.qriban n'existe pas
LINE 8: bk.name AS bankname, bk.iban, bk.qriban, bk....
^
HINT: Peut-être que vous souhaitiez référencer la colonne « bk.iban ».

**Comment by pjaouen** [comment]
solved by adding qriban character varying(39) in bank table

**Comment by Tekki** [comment]
Can you explain how this error was produced?
When you have upgraded at the next login you should get a message 'Dataset will be upgraded to...' and a 'continue' link. Then the script runs that creates the new column to the bank table. Didn't you get this message? Or did you stay logged in during the upgrade?

**Comment by Tekki** [comment]
Closing this, there was no answer to my question.
