### ISSUE TITLE
any docs on using the json api ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [Tekki/sql-ledger#48]
to f.ex. add a payment (of an existing invoice) ?

**Comment by Tekki** [comment]
At the moment there are no docs, but can add something in the next days.

**Comment by lkraav** [comment]
> At the moment there are no docs, but can add something in the next days.

That would be fantastic, wasn't even aware there is an API.

**Comment by Tekki** [comment]
I've added some explanations, there is a link in the readme.
