### ISSUE TITLE
UTF-8: Database Connection

### ISSUE THREAD

**Issue by Tekki** [Tekki/sql-ledger#5]
First step: Let DBD::Pg handle the connection details. We remove all the parameters (besides AutoCommit) and look what happens.

**Comment by lkraav** [comment]
And where do we see this? Shall we set up a joint access throwaway vserver for this (Digital Ocean, Vultr are pretty cheap), or everybody checks for what they see in their own sandbox, or.

**Comment by Tekki** [comment]
That's a good point. 👍 
I simply assumed that everybody in the world has a development environment, or at least can create one with two mouse clicks.
Now it depends on what you want to do. If you want to write code, then you need such an environment, if you only want to test, then you need access to a server where the most recent code runs.

**Comment by lkraav** [comment]
I already have my own production instance, and my patches running successfully. So I'd assume you and I could set something up for joint development, but it would be useful to have the option to make it browser-accessible to whoever we manage to bring in for doing some testing.

**Comment by Tekki** [comment]
This change was made in e72327e61f0247ab4c585c163554bb67a320fcdc. The result looks fine, everything that comes from database is broken. :)
