### ISSUE TITLE
error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory      

### ISSUE THREAD

**Issue by MubashirullahD** [Tekki/sql-ledger#50]
I tried testing Sql-ledger from the docker installation. When I try to create a dataset, I get this error.

`error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory        Is the server running locally and accepting connections on that socket?`

I went with the manual approach and got the same error. What am I doing wrong?

**Comment by Tekki** [comment]
You need a database running somewhere on your system.
If you used the file `docker/docker-compose.yml` to start the container with `docker-compose`, then you already have a second container running PostgreSQL. Check it with `docker container ls`. In this case, if you want to add a new dataset in the admin interface (probably the first thing you want to do), you have to enter 'db' as host name and 'sql-ledger' for both username and password.
If you have a different setup, please describe it in more details.

**Comment by MubashirullahD** [comment]
Dear @Tekki thank you so much. I wasn't entering db in the host of the admin panel. I was following the wrong tutorial.
