### ISSUE TITLE
Extending the API

### ISSUE THREAD

**Issue by MubashirullahD** [Tekki/sql-ledger#51]
Hi. I want to understand how much effort it takes to write the the different methods in /bin/mozilla/api.pl?
We wanted to cover all the functionality through APIs. Many thanks.

**Comment by Tekki** [comment]
If with "all" you mean "really all", then you need maybe 3 years.
It is relatively easy to send the content of the reports as JSON response, but if you want to change data, then you have to map the request data into the format that is expected by the program. You see an example in `sub add_payment`. This is already complicated for something as simple as a payment. For objects like invoices, it would be a lot of work. And every time the backend changes you have to adapt your subroutines.
I recommend that you concentrate on the functionality you actually need and then take the approach to imitate the behavior of the browser. In Perl, you can use [LWP::UserAgent](https://metacpan.org/pod/LWP::UserAgent) and [HTML::Form](https://metacpan.org/pod/HTML::Form) for that. You create an authenticated user agent and then step by step do everything in the program that you would do manually in the browser. Like this, you can add customers, create invoices with 20 rows, send them by e-mail, and everything else.

**Comment by MubashirullahD** [comment]
Dear Tekki,
Thank you so much for your guidance. I've started with the Form approach and it works just fine. 

To anyone else interested, this is what the code will look like in Python for creating an invoice:

```py
import requests


# http://localhost/sql-ledger/is.pl?path=bin/mozilla&action=add&level=AR--Sales Invoice&login=admin@mydataset&js=1&type=invoice


post = {
    "id": 0,
    "type": "invoice",
    "title": "Add Sales Invoice",
    "vc": "customer",
    "discount": 0,
    "oldtransdate": "02-03-2022",
    "oldduedate": "02-03-2022",
    "defaultcurrency": "USD",
    "precision": 2,
    "remittancevoucher": 0,
    "reference_rows": 1,
    "olddepartment": "woolangs--10073",
    "company": "Roomy",
    "selectcustomer": "mediHealth--10071%0a",
    "selectAR": "1200--Accounts%20Receivables%0a",
    "selectAR_paid": "1060--Checking%20Account%0a1065--Petty%20Cash%0a1206--HBL-%20Credit%20Card%0a",
    "selectformname": "invoice--Invoice%0apick_list--Pick%20List%0apacking_list--Packing%20List%0abarcode--Barcode",
    "selectcurrency": "USD%0aCAD%0aEUR%0a",
    "selectdepartment": "%0awoolangs--10073%0a",
    "customer_id": 10071,
    "oldcustomer": "mediHealth--10071",
    "oldcustomernumber": 1,
    "customer": "mediHealth--10071",
    "customernumber": 1,
    "AR": "1200--Accounts Receivables",
    "currency": "USD",
    "department": "woolangs--10073",
    "employee": "--0",
    "transdate": "02-03-2022",
    "duedate": "02-03-2022",
    "weightunit": "kg",
    "runningnumber_1": 1,
    "partnumber_1": 2030,
    "description_1": "Security",
    "qty_1": 1,
    "sellprice_1": 200.00,
    # discount_1:
    "oldqty_1": 1,
    "id_1": 10075,
    "weight_1": 0,
    "sell_1": 200.00,
    "taxaccounts_1": 2310,
    "pricematrix_1": "0:100",
    "sku_1": 2020,
    "assembly_1": 0,
    "income_accno_id_1": 10074,
    "expense_accno_id_1": 10041,
    "checkinventory_1": 0,
    "cost_1": 0,
    "netweight_1": 0,
    "grossweight_1": 0,
    "volume_1": 0,
    "runningnumber_2": 2,
    "cost_2": 0,
    "netweight_2": 0,
    "grossweight_2": 0,
    "volume_2": 0,
    "oldcurrency": "USD",
    "cd_available": 0,
    "AR_paid_1": "1060--Checking Account",
    "paidaccounts": 1,
    #"oldinvtotal": 100,
    #"oldtotalpaid": 0,
    "payment_accno": "1060--Checking%20Account",
    # payment_method:
    "roundchange": "% 3d0.01",
    "selectformname": "invoice--Invoice%0apick_list--Pick%20List%0apacking_list--Packing%20List%0abarcode--Barcode",
    "formname": "invoice",
    "format": "html",
    "media": "screen",
    "copies": 1,
    "sortby": "runningnumber",
    "action": "Post",
    "rowcount": 2,
    "path": "bin/mozilla",
    "login": "admin@mydataset",
    'password': 'sql-ledger'
}


r = requests.post('http://localhost/sql-ledger/is.pl', post)
print(r.status_code)
print(r.text)
```

**Comment by Tekki** [comment]
This approach works, but it has some drawbacks, especially that you have to find out all the different IDs (customer_id, id_1, id_2), add description and price of the parts, and so on. What I meant is that you use a client object (as in your example in #52). On Python this is probably `http.client.HTTPConnection`. Then you work in several steps:
- set `password=...&action=login`, post to login.pl
- set `action=add&type=invoice`, post to is.pl (take the URL from the menu)
- extract the `<form>` from the response
- set `customernumber=...&action=update`, post to is.pl
- extract `<form>`
- set `partnumber_1=...&qty_1=...&action=update`, post to is.pl
- extract `<form>`
- the same for row 2, 3, 4...
- set `action=post` (or print_and_post, whatever you need), post to is.pl

**Comment by Tekki** [comment]
I give you an example in Perl with [Mojolicious](https://metacpan.org/pod/Mojolicious) and [HTML::Form](https://metacpan.org/pod/HTML::Form).
We write an invoice to customer with number `1109` who has bought 5 pieces of part `300016`, 2 pieces of `300011` and one of `300005`:
``` perl
#!/usr/bin/env perl
use Mojo::Base -strict;

use HTML::Form;
use Mojo::Util 'decode';
use Mojo::UserAgent;

# login parameters
my $sl_url      = 'http://localhost/sql-ledger';
my $sl_username = 'myname@mycompany';
my $sl_password = 'mypassword';
my $charset     = 'UTF-8';

# content of the invoice
my $customernumber = 1109;
my $description    = 'Generated Invoice';
my @rows
  = ({partnumber => 300016, qty => 5}, {partnumber => 300011, qty => 2}, {partnumber => 300005},);

# login to SQL-Ledger

my $ua = Mojo::UserAgent->new;
my ($res, %form);
my %sl_params    = (login => $sl_username, path            => 'bin/mozilla',);
my %parse_params = (base  => $sl_url,      content_charset => $charset);

$res
  = $ua->post("$sl_url/login.pl", form => {action => 'login', password => $sl_password, %sl_params})
  ->result;

# open page AR--Sales Invoice

$res = $ua->post("$sl_url/is.pl", form => {action => 'add', type => 'invoice', %sl_params})->result;

# add customer number and description

%form                 = HTML::Form->parse(decode($charset, $res->body), %parse_params)->form;
$form{customernumber} = $customernumber;
$form{description}    = $description;

$form{action} = 'update';
$res = $ua->post("$sl_url/is.pl", form => \%form)->result;

# add rows

my $i;
for my $row (@rows) {
  $i++;

  %form = HTML::Form->parse(decode($charset, $res->body), %parse_params)->form;
  for (keys %$row) {
    $form{"${_}_$i"} = $row->{$_};
  }

  $form{action} = 'update';
  $res = $ua->post("$sl_url/is.pl", form => \%form)->result;
}

# post invoice

%form         = HTML::Form->parse(decode($charset, $res->body), %parse_params)->form;
$form{action} = 'post';
$res          = $ua->post("$sl_url/is.pl", form => \%form)->result;
```

**Comment by MubashirullahD** [comment]
Dear Tekki,
Thank you so much for the detailed example!

I tried writing an equivalent in python and constantly ran into the issue of not being able to update the customer. It would add the items successfully but with respect to the customer, only customernumber field would change, the rest of the values would not, and hence the posting would happen to the same customer everytime. 

I tried the perl script and face a similar issue. The customer it posts to is the one where it did the last transaction. So if I manually go and do a transaction with another customer, the next time I run the script with any changed customernumber, it will not consider that but post to whatever the old customer was.

So my python script only posts to one customer irrespective of the previous customer used for transaction. And the perl script is unable to change customer. I only updated the number and the rows, everything else is the same. 

I can't think of what could be the problem. Its not an issue if customernumber is a hidden input? Its not a value that can be changed from the GUI. Your guidance would be appreciated.
![image](https://user-images.githubusercontent.com/45071858/153001044-86d3319b-b251-426d-b028-c7a5af79db2d.png)

```py
# Source: https://www.thepythoncode.com/article/extracting-and-submitting-web-page-forms-in-python

from bs4 import BeautifulSoup
from requests_html import HTMLSession
from pprint import pprint


def login(url_base):
    """
    Login once
    """
    login = {'login': 'admin@dataset',
             'password': 'sql-ledger', 'path': 'bin/mozilla',
             'action': 'login'}
    res = session.post(url_base + "/login.pl", data=login)
    print("Login Post response", res, res.html.html)


def get_all_forms(url_base, endpoint, data):
    """
    Gets all form tags found on a web page's `url`
    and returns the html details of a form. 
    """
    # POST and GET request
    res = session.post(url_base + endpoint, data=data)
    # res = session.get(url_base + endpoint, data={'login': 'admin@dataset',
    #                                              'path': 'bin/mozilla',
    #                                              'action': 'add', 'type': 'invoice'})

    soup = BeautifulSoup(res.html.html, "html.parser")
    Forms = soup.find_all("form")
    details = _get_form_details(Forms[0])  # Only one form assumed
    return details


def _get_form_details(form):
    """
    Returns the HTML details of a form,
    including action, method and list of form controls (inputs, etc).
    In addition to a form dictionary.
    """
    details = {}
    # get the form action (requested URL)
    action = form.attrs.get("action").lower()
    # get the form method (POST, GET, DELETE, etc)
    # if not specified, GET is the default in HTML
    method = form.attrs.get("method", "get").lower()
    # get all form inputs
    inputs = []
    # form inputs but in dictionary form. This will NOT take duplicate names into account.
    form_input = {}

    for input_tag in form.find_all("input"):
        # get type of input form control
        input_type = input_tag.attrs.get("type", "text")

        # get name attribute
        input_name = input_tag.attrs.get("name")

        # get the default value of that input tag
        input_value = input_tag.attrs.get("value", "")

        # add everything to that list
        inputs.append(
            {"type": input_type, "name": input_name, "value": input_value})

        # add everything to our form dictionary
        form_input[input_name] = input_value

    for select in form.find_all("select"):
        # get the name attribute
        select_name = select.attrs.get("name")

        # set the type as select
        select_type = "select"
        select_options = []

        # the default select value
        select_default_value = ""

        # iterate over options and get the value of each
        for select_option in select.find_all("option"):

            # get the option value used to submit the form
            option_value = select_option.attrs.get("value")
            if option_value:
                select_options.append(option_value)
                if select_option.attrs.get("selected"):
                    # if 'selected' attribute is set, set this option as default
                    select_default_value = option_value

        if not select_default_value and select_options:
            # if the default is not set, and there are options, take the first option as default
            select_default_value = select_options[0]

        # add the select to the inputs list
        inputs.append({"type": select_type, "name": select_name,
                      "values": select_options, "value": select_default_value})

        # add select to our form dictionary
        form_input[select_name] = select_default_value

    for textarea in form.find_all("textarea"):
        # get the name attribute
        textarea_name = textarea.attrs.get("name")

        # set the type as textarea
        textarea_type = "textarea"

        # get the textarea value
        textarea_value = textarea.attrs.get("value", "")

        # add the textarea to the inputs list
        inputs.append(
            {"type": textarea_type, "name": textarea_name, "value": textarea_value})

        # add textarea to our form dictionary
        form_input[textarea_name] = textarea_value

    # put everything to the resulting dictionary
    details["action"] = action
    details["method"] = method
    details["inputs"] = inputs
    details["form"] = form_input
    return details


if __name__ == "__main__":
    base_url = "http://localhost/sql-ledger"
    endpoint = "/is.pl"

    # initialize an HTTP session
    session = HTMLSession()

    # Login
    login(base_url)

    # Add invoice
    add = {'login': 'admin@dataset',
           'path': 'bin/mozilla',
           'action': 'add',
           'type': 'invoice'}
    form_details = get_all_forms(base_url, endpoint, add)

    print("Add invoice part")
    print("="*50, f"form #1", "="*50)
    pprint(form_details["inputs"])

    # Add customer number and description
    #form_details["form"]["selectcustomer"] = "mediHealth--10071%0a"
    form_details["form"]["customer"] = 'mediHealth--10071'
    form_details["form"]["description"] = "Generated Invoice"
    form_details["form"]["action"] = "update"

    form_details = get_all_forms(base_url, endpoint, form_details["form"])

    print("Add Customer part")
    print("="*50, f"form #1", "="*50)
    pprint(form_details["inputs"])

    # Add items to the invoice
    items = [{"partnumber": 2020, "qty": 1}, {"partnumber": 2030, "qty": 1}]

    for i, item in enumerate(items, start=1):
        print(i, item)
        form_details["form"]["partnumber_" + str(i)] = item["partnumber"]
        form_details["form"]["qty_" + str(i)] = item["qty"]
        form_details["form"]["action"] = "update"

        form_details = get_all_forms(base_url, endpoint, form_details["form"])

    print("Add items part")
    print("="*50, f"form #1", "="*50)
    pprint(form_details["inputs"])

    # Add changes to account
    form_details["form"]["AR_paid_1"] = "1060--Checking Account"

    # Post invoice
    form_details["form"]["action"] = "post"
    form_details = get_all_forms(base_url, endpoint, form_details["form"])



```

**Comment by MubashirullahD** [comment]
Update: I added "customer_id" to the perl script and it works.
![image](https://user-images.githubusercontent.com/45071858/153143514-ddfab17b-3500-42e6-a3d7-d3675f395e8d.png)

**Comment by Tekki** [comment]
> Update: I added "customer_id" to the perl script and it works.

You should set the dropdown limit in the user preferences to zero, so you have no dropdown for the customers in the browser. Otherwise the program behaves differently, depending on the numbers of customers you have. I forgot about this, sorry.

Looking at you code I wonder how you parse the checkboxes.

**Comment by MubashirullahD** [comment]
Update: The same python code seems to work now that the preferences have been set. I've manually compared the form scrapped with the python code and with regards to checkboxes, they are part of "input" so  form.find_all("input") suffices.
The only elements I did not see were a few select options. For some reason "formname" for instance was not scrapped with this code but did show up in the dictionary equivalent.

Pasting sample output of scrapped form_details below. Thank you so much. 

{'action': 'is.pl',
 'form': {'AR': '1200--Accounts Receivables',
          'AR_paid_1': '1060--Checking Account',
          '_updated': '',
          'action': 'New Number',
          'address1': '',
          'address2': '',
          'allbox': '1',
          'assembly_1': '',
          'audittrail': '',
          'bcc': '',
          'bin_1': '',
          'business': '',
          'callback': 'is.pl?action=add&type=invoice&login=admin@mydataset&path=bin/mozilla',
          'cashovershort': '',
          'cc': '',
          'cd_available': '0',
          'cdt': '',
          'checkinventory_1': '',
          'city': '',
          'cleared_1': '',
          'closedto': '',
          'company': 'Roomy',
          'copies': '1',
          'cost_1': '0',
          'costvendor_1': '',
          'costvendorid_1': '',
          'country': '',
          'creditlimit': '0',
          'creditremaining': '-28800',
          'currency': 'USD',
          'customer': 'Mubashir',
          'customer_id': '10092',
          'customernumber': '2',
          'customerponumber_1': '',
          'datepaid_1': '',
          'dcn': '',
          'defaultcurrency': 'USD',
          'deliverydate_1': '',
          'department': 'woolangs--10073',
          'description': '',
          'description_1': '',
          'discount': '0',
          'discount_1': '',
          'duedate': '02-09-2022',
          'email': '',
          'emailed': '',
          'employee': '--0',
          'expense_accno_id_1': '',
          'expires_1': '',
          'format': 'html',
          'formname': 'invoice',
          'generate': '',
          'grossweight_1': '0',
          'grouppartsgroup': '',
          'groupprojectnumber': '',
          'helpref': '',
          'id': '0',
          'id_1': '',
          'income_accno_id_1': '',
          'intnotes': '',
          'inventory_accno_id_1': '',
          'invnumber': '',
          'invoice_emailed': '1',
          'invoice_printed': '1',
          'itemnotes_1': '',
          'kit_1': '',
          'lastcost_1': '',
          'lineitemdetail_1': '',
          'listprice_1': '',
          'locked': '',
          'login': 'admin@mydataset',
          'lot_1': '',
          'make_1': '',
          'media': 'screen',
          'memo_1': '',
          'message': '',
          'model_1': '',
          'netweight_1': '0',
          'notes': '',
          'oldcurrency': 'USD',
          'oldcustomer': 'Mubashir--10092',
          'oldcustomernumber': '2',
          'olddepartment': 'woolangs--10073',
          'oldduedate': '02-09-2022',
          'oldinvtotal': '0',
          'oldqty_1': '0',
          'oldship_1': '',
          'oldterms': '',
          'oldtotalpaid': '0',
          'oldtransdate': '02-09-2022',
          'oldwarehouse': '',
          'onhand_1': '',
          'onhold': '1',
          'order_id': '',
          'orderitems_id_1': '',
          'ordernumber_1': '',
          'ordnumber': '',
          'package_1': '',
          'paid_1': '',
          'paidaccounts': '1',
          'partnumber_1': '',
          'path': 'bin/mozilla',
          'payment_accno': '--',
          'payment_method': '--0',
          'ponumber': '',
          'precision': '2',
          'pricegroup': '',
          'pricematrix_1': '',
          'printed': '',
          'projectnumber_1': '',
          'qty_1': '',
          'queued': '',
          'quonumber': '',
          'readonly': '',
          'recurring': '',
          'reference_rows': '1',
          'referencearchive_id_1': '',
          'referencecode_1': '',
          'referenceconfidential_1': '1',
          'referencedescription_1': '',
          'referencefilename_1': '',
          'referencefolder_1': '',
          'referencetmpfile_1': '',
          'referenceurl': '',
          'remittancevoucher': '0',
          'roundchange': '%3d0.01',
          'rowcount': '1',
          'runningnumber_1': '1',
          'selectAR': '1200--Accounts%20Receivables%0a',
          'selectAR_discount': '',
          'selectAR_paid': '1060--Checking%20Account%0a1065--Petty%20Cash%0a1206--HBL-%20Credit%20Card%0a',
          'selectcurrency': 'USD%0aCAD%0aEUR%0a',
          'selectcustomer': '',
          'selectdepartment': '%0awoolangs--10073%0a',
          'selectemployee': '',
          'selectformname': 'invoice--Invoice%0apick_list--Pick%20List%0apacking_list--Packing%20List%0abarcode--Barcode',
          'selectlanguage': '',
          'selectpartsgroup': '',
          'selectpaymentmethod': '',
          'selectprinter': '',
          'selectprojectnumber': '',
          'selectwarehouse': '',
          'sell_1': '',
          'sellprice_1': '',
          'serialnumber_1': '',
          'shipped': '',
          'shippingpoint': '',
          'shiptoaddress1': '',
          'shiptoaddress2': '',
          'shiptocity': '',
          'shiptocontact': '',
          'shiptocountry': '',
          'shiptoemail': '',
          'shiptofax': '',
          'shiptoname': '',
          'shiptophone': '',
          'shiptorecurring': '',
          'shiptostate': '',
          'shiptozipcode': '',
          'shipvia': '',
          'sku_1': '',
          'sortby': 'bin',
          'source_1': '',
          'state': '',
          'subject': '',
          'taxaccounts': '',
          'taxaccounts_1': '',
          'terms': '',
          'title': 'Add Sales Invoice',
          'tradediscount': '',
          'transdate': '02-09-2022',
          'type': 'invoice',
          'unit_1': '',
          'vc': 'customer',
          'volume_1': '0',
          'vr_id_1': '',
          'waybill': '',
          'weight_1': '',
          'weightunit': 'kg',
          'zipcode': ''},
 'inputs': [{'name': 'id', 'type': 'hidden', 'value': '0'},
            {'name': 'type', 'type': 'hidden', 'value': 'invoice'},
            {'name': 'printed', 'type': 'hidden', 'value': ''},
            {'name': 'emailed', 'type': 'hidden', 'value': ''},
            {'name': 'queued', 'type': 'hidden', 'value': ''},
            {'name': 'title', 'type': 'hidden', 'value': 'Add Sales Invoice'},
            {'name': 'vc', 'type': 'hidden', 'value': 'customer'},
            {'name': 'discount', 'type': 'hidden', 'value': '0'},
            {'name': 'creditlimit', 'type': 'hidden', 'value': '0'},
            {'name': 'creditremaining', 'type': 'hidden', 'value': '-28800'},
            {'name': 'tradediscount', 'type': 'hidden', 'value': ''},
            {'name': 'business', 'type': 'hidden', 'value': ''},
            {'name': 'closedto', 'type': 'hidden', 'value': ''},
            {'name': 'locked', 'type': 'hidden', 'value': ''},
            {'name': 'shipped', 'type': 'hidden', 'value': ''},
            {'name': 'oldtransdate', 'type': 'hidden', 'value': '02-09-2022'},
            {'name': 'oldduedate', 'type': 'hidden', 'value': '02-09-2022'},
            {'name': 'recurring', 'type': 'hidden', 'value': ''},
            {'name': 'defaultcurrency', 'type': 'hidden', 'value': 'USD'},
            {'name': 'oldterms', 'type': 'hidden', 'value': ''},
            {'name': 'cdt', 'type': 'hidden', 'value': ''},
            {'name': 'precision', 'type': 'hidden', 'value': '2'},
            {'name': 'order_id', 'type': 'hidden', 'value': ''},
            {'name': 'remittancevoucher', 'type': 'hidden', 'value': '0'},
            {'name': 'reference_rows', 'type': 'hidden', 'value': '1'},
            {'name': 'referenceurl', 'type': 'hidden', 'value': ''},
            {'name': 'oldwarehouse', 'type': 'hidden', 'value': ''},
            {'name': 'olddepartment',
             'type': 'hidden',
             'value': 'woolangs--10073'},
            {'name': 'company', 'type': 'hidden', 'value': 'Roomy'},
            {'name': 'selectcustomer', 'type': 'hidden', 'value': ''},
            {'name': 'selectAR',
             'type': 'hidden',
             'value': '1200--Accounts%20Receivables%0a'},
            {'name': 'selectAR_paid',
             'type': 'hidden',
             'value': '1060--Checking%20Account%0a1065--Petty%20Cash%0a1206--HBL-%20Credit%20Card%0a'},
            {'name': 'selectAR_discount', 'type': 'hidden', 'value': ''},
            {'name': 'selectformname',
             'type': 'hidden',
             'value': 'invoice--Invoice%0apick_list--Pick%20List%0apacking_list--Packing%20List%0abarcode--Barcode'},
            {'name': 'selectcurrency',
             'type': 'hidden',
             'value': 'USD%0aCAD%0aEUR%0a'},
            {'name': 'selectpartsgroup', 'type': 'hidden', 'value': ''},
            {'name': 'selectprojectnumber', 'type': 'hidden', 'value': ''},
            {'name': 'selectdepartment',
             'type': 'hidden',
             'value': '%0awoolangs--10073%0a'},
            {'name': 'selectwarehouse', 'type': 'hidden', 'value': ''},
            {'name': 'selectemployee', 'type': 'hidden', 'value': ''},
            {'name': 'selectlanguage', 'type': 'hidden', 'value': ''},
            {'name': 'selectpaymentmethod', 'type': 'hidden', 'value': ''},
            {'name': 'selectprinter', 'type': 'hidden', 'value': ''},
            {'name': 'customer_id', 'type': 'hidden', 'value': '10092'},
            {'name': 'oldcustomer',
             'type': 'hidden',
             'value': 'Mubashir--10092'},
            {'name': 'quonumber', 'type': 'hidden', 'value': ''},
            {'name': 'oldcustomernumber', 'type': 'hidden', 'value': '2'},
            {'name': 'action', 'type': 'hidden', 'value': 'update'},
            {'name': 'customer', 'type': 'text', 'value': 'Mubashir'},
            {'name': 'customernumber', 'type': 'text', 'value': '2'},
            {'name': 'shippingpoint', 'type': 'text', 'value': ''},
            {'name': 'shipvia', 'type': 'text', 'value': ''},
            {'name': 'waybill', 'type': 'text', 'value': ''},
            {'name': 'employee', 'type': 'hidden', 'value': '--0'},
            {'name': 'invnumber', 'type': 'text', 'value': ''},
            {'name': 'ordnumber', 'type': 'text', 'value': ''},
            {'name': 'transdate', 'type': 'text', 'value': '02-09-2022'},
            {'name': 'duedate', 'type': 'text', 'value': '02-09-2022'},
            {'name': 'terms', 'type': 'text', 'value': ''},
            {'name': 'ponumber', 'type': 'text', 'value': ''},
            {'name': 'referencedescription_1', 'type': 'text', 'value': ''},
            {'name': 'referenceconfidential_1',
             'type': 'checkbox',
             'value': '1'},
            {'name': 'referencecode_1', 'type': 'hidden', 'value': ''},
            {'name': 'referencetmpfile_1', 'type': 'hidden', 'value': ''},
            {'name': 'referencearchive_id_1', 'type': 'hidden', 'value': ''},
            {'name': 'referencefilename_1', 'type': 'hidden', 'value': ''},
            {'name': 'referencefolder_1', 'type': 'hidden', 'value': ''},
            {'name': 'description', 'type': 'text', 'value': ''},
            {'name': 'shiptoname', 'type': 'hidden', 'value': ''},
            {'name': 'shiptoaddress1', 'type': 'hidden', 'value': ''},
            {'name': 'shiptoaddress2', 'type': 'hidden', 'value': ''},
            {'name': 'shiptocity', 'type': 'hidden', 'value': ''},
            {'name': 'shiptostate', 'type': 'hidden', 'value': ''},
            {'name': 'shiptozipcode', 'type': 'hidden', 'value': ''},
            {'name': 'shiptocountry', 'type': 'hidden', 'value': ''},
            {'name': 'shiptocontact', 'type': 'hidden', 'value': ''},
            {'name': 'shiptophone', 'type': 'hidden', 'value': ''},
            {'name': 'shiptofax', 'type': 'hidden', 'value': ''},
            {'name': 'shiptoemail', 'type': 'hidden', 'value': ''},
            {'name': 'shiptorecurring', 'type': 'hidden', 'value': ''},
            {'name': 'address1', 'type': 'hidden', 'value': ''},
            {'name': 'address2', 'type': 'hidden', 'value': ''},
            {'name': 'city', 'type': 'hidden', 'value': ''},
            {'name': 'state', 'type': 'hidden', 'value': ''},
            {'name': 'zipcode', 'type': 'hidden', 'value': ''},
            {'name': 'country', 'type': 'hidden', 'value': ''},
            {'name': 'message', 'type': 'hidden', 'value': ''},
            {'name': 'email', 'type': 'hidden', 'value': ''},
            {'name': 'subject', 'type': 'hidden', 'value': ''},
            {'name': 'cc', 'type': 'hidden', 'value': ''},
            {'name': 'bcc', 'type': 'hidden', 'value': ''},
            {'name': 'taxaccounts', 'type': 'hidden', 'value': ''},
            {'name': 'dcn', 'type': 'hidden', 'value': ''},
            {'name': 'pricegroup', 'type': 'hidden', 'value': ''},
            {'name': 'weightunit', 'type': 'hidden', 'value': 'kg'},
            {'name': 'allbox', 'type': 'checkbox', 'value': '1'},
            {'name': 'runningnumber_1', 'type': 'text', 'value': '1'},
            {'name': 'partnumber_1', 'type': 'text', 'value': ''},
            {'name': 'description_1', 'type': 'text', 'value': ''},
            {'name': 'lineitemdetail_1', 'type': 'checkbox', 'value': ''},
            {'name': 'qty_1', 'type': 'text', 'value': ''},
            {'name': 'unit_1', 'type': 'text', 'value': ''},
            {'name': 'sellprice_1', 'type': 'text', 'value': ''},
            {'name': 'discount_1', 'type': 'text', 'value': ''},
            {'name': 'oldqty_1', 'type': 'hidden', 'value': '0'},
            {'name': 'oldship_1', 'type': 'hidden', 'value': ''},
            {'name': 'orderitems_id_1', 'type': 'hidden', 'value': ''},
            {'name': 'id_1', 'type': 'hidden', 'value': ''},
            {'name': 'weight_1', 'type': 'hidden', 'value': ''},
            {'name': 'sell_1', 'type': 'hidden', 'value': ''},
            {'name': 'listprice_1', 'type': 'hidden', 'value': ''},
            {'name': 'lastcost_1', 'type': 'hidden', 'value': ''},
            {'name': 'taxaccounts_1', 'type': 'hidden', 'value': ''},
            {'name': 'pricematrix_1', 'type': 'hidden', 'value': ''},
            {'name': 'sku_1', 'type': 'hidden', 'value': ''},
            {'name': 'onhand_1', 'type': 'hidden', 'value': ''},
            {'name': 'bin_1', 'type': 'hidden', 'value': ''},
            {'name': 'assembly_1', 'type': 'hidden', 'value': ''},
            {'name': 'inventory_accno_id_1', 'type': 'hidden', 'value': ''},
            {'name': 'income_accno_id_1', 'type': 'hidden', 'value': ''},
            {'name': 'expense_accno_id_1', 'type': 'hidden', 'value': ''},
            {'name': 'kit_1', 'type': 'hidden', 'value': ''},
            {'name': 'lot_1', 'type': 'hidden', 'value': ''},
            {'name': 'expires_1', 'type': 'hidden', 'value': ''},
            {'name': 'checkinventory_1', 'type': 'hidden', 'value': ''},
            {'name': 'make_1', 'type': 'hidden', 'value': ''},
            {'name': 'model_1', 'type': 'hidden', 'value': ''},
            {'name': 'deliverydate_1', 'type': 'hidden', 'value': ''},
            {'name': 'itemnotes_1', 'type': 'hidden', 'value': ''},
            {'name': 'serialnumber_1', 'type': 'hidden', 'value': ''},
            {'name': 'ordernumber_1', 'type': 'hidden', 'value': ''},
            {'name': 'customerponumber_1', 'type': 'hidden', 'value': ''},
            {'name': 'projectnumber_1', 'type': 'hidden', 'value': ''},
            {'name': 'cost_1', 'type': 'hidden', 'value': '0'},
            {'name': 'costvendor_1', 'type': 'hidden', 'value': ''},
            {'name': 'costvendorid_1', 'type': 'hidden', 'value': ''},
            {'name': 'package_1', 'type': 'hidden', 'value': ''},
            {'name': 'netweight_1', 'type': 'hidden', 'value': '0'},
            {'name': 'grossweight_1', 'type': 'hidden', 'value': '0'},
            {'name': 'volume_1', 'type': 'hidden', 'value': '0'},
            {'name': 'audittrail', 'type': 'hidden', 'value': ''},
            {'name': 'oldcurrency', 'type': 'hidden', 'value': 'USD'},
            {'name': 'selectpartsgroup', 'type': 'hidden', 'value': ''},
            {'name': 'selectprojectnumber', 'type': 'hidden', 'value': ''},
            {'name': 'cd_available', 'type': 'hidden', 'value': '0'},
            {'name': 'cleared_1', 'type': 'hidden', 'value': ''},
            {'name': 'vr_id_1', 'type': 'hidden', 'value': ''},
            {'name': 'datepaid_1', 'type': 'text', 'value': ''},
            {'name': 'source_1', 'type': 'text', 'value': ''},
            {'name': 'memo_1', 'type': 'text', 'value': ''},
            {'name': 'paid_1', 'type': 'text', 'value': ''},
            {'name': 'paidaccounts', 'type': 'hidden', 'value': '1'},
            {'name': 'oldinvtotal', 'type': 'hidden', 'value': '0'},
            {'name': 'oldtotalpaid', 'type': 'hidden', 'value': '0'},
            {'name': 'payment_accno', 'type': 'hidden', 'value': '--'},
            {'name': 'payment_method', 'type': 'hidden', 'value': '--0'},
            {'name': 'roundchange', 'type': 'hidden', 'value': '%3d0.01'},
            {'name': 'cashovershort', 'type': 'hidden', 'value': ''},
            {'name': 'selectformname',
             'type': 'hidden',
             'value': 'invoice--Invoice%0apick_list--Pick%20List%0apacking_list--Packing%20List%0abarcode--Barcode'},
            {'name': 'copies', 'type': 'text', 'value': '1'},
            {'name': 'onhold', 'type': 'checkbox', 'value': '1'},
            {'name': 'invoice_printed', 'type': 'checkbox', 'value': '1'},
            {'name': 'invoice_emailed', 'type': 'checkbox', 'value': '1'},
            {'name': 'groupprojectnumber', 'type': 'checkbox', 'value': ''},
            {'name': 'grouppartsgroup', 'type': 'checkbox', 'value': ''},
            {'name': 'sortby', 'type': 'radio', 'value': 'runningnumber'},
            {'name': 'sortby', 'type': 'radio', 'value': 'partnumber'},
            {'name': 'sortby', 'type': 'radio', 'value': 'description'},
            {'name': 'sortby', 'type': 'radio', 'value': 'bin'},
            {'name': 'action', 'type': 'submit', 'value': 'Update'},
            {'name': 'action', 'type': 'submit', 'value': 'Preview'},
            {'name': 'action', 'type': 'submit', 'value': 'Print'},
            {'name': 'action', 'type': 'submit', 'value': 'Post'},
            {'name': 'action', 'type': 'submit', 'value': 'Ship to'},
            {'name': 'action', 'type': 'submit', 'value': 'E-mail'},
            {'name': 'action', 'type': 'submit', 'value': 'Print and Post'},
            {'name': 'action', 'type': 'submit', 'value': 'Schedule'},
            {'name': 'action', 'type': 'submit', 'value': 'New Number'},
            {'name': 'helpref', 'type': 'hidden', 'value': ''},
            {'name': 'generate', 'type': 'hidden', 'value': ''},
            {'name': 'rowcount', 'type': 'hidden', 'value': '1'},
            {'name': 'readonly', 'type': 'hidden', 'value': ''},
            {'name': 'callback',
             'type': 'hidden',
             'value': 'is.pl?action=add&type=invoice&login=admin@mydataset&path=bin/mozilla'},
            {'name': 'path', 'type': 'hidden', 'value': 'bin/mozilla'},
            {'name': 'login',
             'type': 'hidden',
             'value': 'admin@mydataset'},
            {'name': '_updated', 'type': 'hidden', 'value': ''},
            {'name': 'AR',
             'type': 'select',
             'value': '1200--Accounts Receivables',
             'values': ['1200--Accounts Receivables']},
            {'name': 'currency',
             'type': 'select',
             'value': 'USD',
             'values': ['USD', 'CAD', 'EUR']},
            {'name': 'department',
             'type': 'select',
             'values': ['html', 'xml', 'txt', 'ps', 'pdf']},
            {'name': 'media',
             'type': 'select',
             'value': 'screen',
             'values': ['screen', 'queue']},
            {'name': 'notes', 'type': 'textarea', 'value': ''},
            {'name': 'intnotes', 'type': 'textarea', 'value': ''}],
 'method': 'post'}

**Comment by MubashirullahD** [comment]
What do you recommend with regards to running database queries in case the reports do not provide all the information conveniently?
Thank you.

**Comment by MubashirullahD** [comment]
> What do you recommend with regards to running database queries in case the reports do not provide all the information conveniently? Thank you.

**Using the ’System–Maintenance–Monitor’ menu, you can run any individual
SQL query or command directly on your SQL-Ledger database.**

![image](https://user-images.githubusercontent.com/45071858/153819852-427fddda-c55d-4fe4-9927-0f9b32559fab.png)

![image](https://user-images.githubusercontent.com/45071858/153819900-56c80f12-b0e3-4de7-859d-1010cda62ded.png)

**Comment by Tekki** [comment]
@MubashirullahD You can now use an access token for the API calls. Take a look at the [docs](https://github.com/Tekki/sql-ledger/blob/full/doc/api.md).
