### ISSUE TITLE
SQL queries for extending use case

### ISSUE THREAD

**Issue by MubashirullahD** [Tekki/sql-ledger#53]
If I want to create a new table for Folio. By my current understanding, recording data into this additional table should not have any impact on all the other operations. Would it be a bad idea to use the monitor panel to programmatically create entries into the Folio?

**Comment by MubashirullahD** [comment]
I have another case I can easily do with a query. I want to go to the Account Transaction table and simply change the account id of one transaction to another account.

**Comment by Tekki** [comment]
Why don't you open the transaction to change the account?

**Comment by Tekki** [comment]
> If I want to create a new table for Folio. By my current understanding, recording data into this additional table should not have any impact on all the other operations. Would it be a bad idea to use the monitor panel to programmatically create entries into the Folio?

What is the idea behind that? A table that is not related to anything else doesn't have to be in the SQL-Ledger database.

**Comment by MubashirullahD** [comment]
> Why don't you open the transaction to change the account?

Perhaps I'm turning this into an XY Problem. I think it would be better to explain the issue. One of the use cases I have to support is BTC Checkouts (Bill To Company). The customer pays their charges but the rest need to be paid by the customer's company. So we will make the payment on BTC and let the customer check out. Later on, the back office will collect all invoice which were paid as BTC payments and make a new cumulative invoice that will be send to the companies to make the actual payment. 

In the new invoice, the service we add is called City Ledger Billing. 
![image](https://user-images.githubusercontent.com/45071858/154452090-c2a8d324-e072-49b0-b2be-74a7d3061b24.png)

Reconciling this new invoice is the tricky part because we don't want to hit the income account twice.


![image](https://user-images.githubusercontent.com/45071858/154452526-361749dd-d55a-42dc-854a-ba3338c559ec.png)

This is the account we want to change from an Income account like Room rent to an asset account.

**Comment by ledger123** [comment]
Hi Mubashir,

Life is tough with SQL-Ledger. Took us 6 years to figure out. :-)

Regards

**Comment by MubashirullahD** [comment]
Hi Saqib,

Six years is an incredibly long time. What would you do differently if you could go back today? Would you build something from scratch?

Best Regards

**Comment by Tekki** [comment]
@ledger123 and @MubashirullahD : such posts look rather off-topic to me. Could you please move this conversation to another place?

**Comment by Tekki** [comment]
> One of the use cases I have to support is BTC Checkouts (Bill To Company). The customer pays their charges but the rest need to be paid by the customer's company. So we will make the payment on BTC and let the customer check out. Later on, the back office will collect all invoice which were paid as BTC payments and make a new cumulative invoice that will be send to the companies to make the actual payment.

So you are looking for this?

Invoice 1

| Description | Account | | |
|-|-|-|-|
| Purchases | Income | | 1000 |
| Paid by company | BTC | 880 | |
| Payment employee | Bank | 120 | |


Invoice 2

| Description | Account | | |
|-|-|-|-|
| Outstanding amount | BTC | | 880 |
| Payment company | Bank | 120 | |

If this is correct, then you could add BTC as income and expense account to "City ledger billing" and use this for both transactions on BTC.

**Comment by MubashirullahD** [comment]
Yes, we are looking for something like this.


<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invoice 1</p>

Description | Account |   |  
-- | -- | -- | --
Purchases | Income |   | 1000
Paid by company | BTC | 880 |  
Payment employee | Bank | 120 |  

<br class="Apple-interchange-newline">
</body>
</html>


<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invoice 2</p>

Description | Account |   |  
-- | -- | -- | --
Purchases | Income |   | 1000
Paid by company | BTC | 900 |  
Payment employee | Bank | 100 |  

<br class="Apple-interchange-newline">
</body>
</html>


<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invoice 3 (Aggregate of Invoice 1 and 2)</p>

Description | Account |   |  
-- | -- | -- | --
Purchases | Account Receivable | 1780  | 
Paid by company | City Ledge Control Account | | 1780  

<br class="Apple-interchange-newline">
</body>
</html>



<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invoice 4</p>

Description | Account |   |  
-- | -- | -- | --
Payment Received | Bank | 1780   | 
Payment company | Account Receivable | |  1780

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span> </span></p>
</body>
</html>

We need away to **aggregate**  the previous invoices into a new invoice without the new invoice incurring sale income account.

**Comment by Tekki** [comment]
Closing this issue, as there is no more activity.
