### ISSUE TITLE
Problem with vendor invoice for kits

### ISSUE THREAD

**Issue by 5oley** [Tekki/sql-ledger#57]
Hi Everyone,
I've been trying to use the kit functionality in the software but keep running into a problem.  I am going to use hot dog for my example. 
I purchase hot dogs by the case, and sell them by the pack. The case has 24 packs..
In SQL Ledger, I create an inventory item for 1 pack of hot dog, and I create a kit of 24 packs I call it a hot dog case.  When I sell, I can sell a pack, or multiple packs, or 1 case with no problem. The client invoice shows the right amount. But when I purchase, the vendor invoice shows the correct amount when I open it, but when I look it up either in the GL, payment window, or reports, it shows the cost one pack times 24 packs. 
My work around right now is to enter the cost of one pack, and use the #cases x 24 packs as my quantity. I am able to duplicate this in the main branch by dws, and this version as well. Am I missing a setting, or something?
Below are the screenshots.

https://imgur.com/UmtY8zv
https://imgur.com/Qf8izNT
https://imgur.com/ret9BIG
https://imgur.com/vS2VXZk
https://imgur.com/lqdP675
https://imgur.com/ULMkaQG

**Comment by Tekki** [comment]
You're correct. Tested it on our server and it looks wrong to me too.
In your screenshots I noticed that you use the DWS version. Ever considered to switch to the code from this repo? If you want this to be solved on the DWS version you have to reach out for them.

**Comment by 5oley** [comment]
Hi,
Thank you for looking into it. I have switched to this repo for a couple of months now.  I got lazy and used some old screenshots. 

Thank you,

**Comment by Tekki** [comment]
There are more problems with kits when they are used in a purchase order. Seems they were never intended to be purchased.

**Comment by 5oley** [comment]
You are right. I did not mention this part. If you create a PO, it creates a debit. I checked in the official manual, and on the website, it doesn't say much if anything on how the kits feature supposed to work.

**Comment by Tekki** [comment]
I was speaking of the logistics side of the purchase orders. Next point is that in invoides the last cost isn't updated.
In my opinion it doesn't make sense to look at a single detail if the whole functionality is broken.

**Comment by Tekki** [comment]
Closing this issue because there is not feedback.
In any case, it seems to me that it's nearly impossible to make kits working correctly on the purchase side.
