### ISSUE TITLE
issue with balance sheet

### ISSUE THREAD

**Issue by mhk00123** [Tekki/sql-ledger#58]
Hello Tekki, I am a old user from Macau, I've use this system for long time. Today I got a problem when I create a balance sheet. 

![d55dc5db268c308a4a320aa4cdb14c8](https://user-images.githubusercontent.com/7094966/219268473-40d248c1-7b46-40b6-87a2-31cfec5b85a6.png)
As you see in the screenshot,  there are two row in balance sheet, have no name,  It's value is sum of cash and assets(Account No.1xxx), and some payable (Account No. 21xx). But this two value will not effect the Total current assets. It just show the sum, and i dont know how to cancel it. 

So the problem is  just want to cancel those two row in balance sheet, how can I do it?

Thank you!

**Comment by Tekki** [comment]
Sorry, if I get no answer I can't help.
