### ISSUE TITLE
Update of Turkish translation

### ISSUE THREAD

**Issue by sse450** [Tekki/sql-ledger#62]
Just wanted to clarify something.

Newly created utf folders in locale of Tekki version don't have locales.pl. Can we copy it from other folders or is there any change in translation procedure?

If I submit a translated "all" file, is that OK for you?

**Comment by Tekki** [comment]
> Newly created utf folders in locale of Tekki version don't have locales.pl. Can we copy it from other folders or is there any change in translation procedure?

You can take the `locales.pl` from `chd_utf` and call it with `/.locales.pl -a -m`. There was an error in the script from DWS for around 10 years that it didn't create the `all` file, not sure if it's fixed now.

> 
> If I submit a translated "all" file, is that OK for you?

Yes, that't okay. And if you want to change some word for individual screens, ask me for more instructions before you start to edit individual files.

You don't have to translate all the new words from my own or the newer DWS versions. Important are "Recently Used" (the title on the start screen) and "Spreadsheet". I'll check your translation and then tell you what is missing.

**Comment by Tekki** [comment]
Do you already have a first version of the `all` file that you can attach to this issue?

**Comment by sse450** [comment]
I have, but not tested thoroughly.  Hope there is no syntax error. As Github doesn't accept files without extension, I had to add .txt extension.
[all.txt](https://github.com/Tekki/sql-ledger/files/15238840/all.txt)

**Comment by Tekki** [comment]
I'll add it to version 42, then you can test it. But before I need some more translations from you:
```
  'Continue?'                   => '',
  'Dataset Size'                => '',
  'Drag and Drop'               => '',
  'File is too big! Allowed are:' => '',
  'Finished'                    => '',
  'Maximum Upload Size'         => '',
  'Perl Modules'                => '',
  'Reference Documents URL'     => '',
  'Uploading...'                => '',
```

**Comment by Tekki** [comment]
Is there no other translation for POS (point of sale)?
```
  'Add POS Invoice'             => 'POS Faturası Ekle',
  'Edit POS Invoice'            => 'POS Faturası Düzenle',
  'POS'                         => 'POS',
  'POS Button'                  => 'POS Butonu',
  'POS Invoice'                 => 'POS Faturası',
```

**Comment by Tekki** [comment]
> There are only those 5 lines in the `all` file regarding POS. I also checked the `all` in chd_utf. Same 5 lines only.

I was just wondering if there is no other word for POS in your language. We leave it like that.

**Comment by sse450** [comment]
Probably there are some more texts in the `all` file related with POS, but without "POS" word in the line. But, I don't know which line is for which module. I think, all the "POS" related lines have already been translated.

**Comment by Tekki** [comment]
Added to version 42 through 938c76c3813859f8d5d0213821f0084ce336ae54.

Thanks for your contributions to this project!
