### ISSUE TITLE
Problems with login on Tekki version

### ISSUE THREAD

**Issue by sse450** [Tekki/sql-ledger#63]
Dear Tekki,
Unfortunately, it is again me. Sorry for the inconvenience I create.
Last time, I installed tekki 3.2.12.40 on Alma Linux 9 (perl v5.32.1) without any problem. This time I need to install tekki 3.2.12.40 on another server, Alma Linux 8.
AL8 has a working SL (3.2.12DWS), surely without unicode support. I replaced all files with tekki 3.2.12.40 and transferred users and templates from DWS. But no matter what I did, I couldn't get access to login.pl page. It briefly shows index.html, then gives "500 Internal Server Error".
Just for testing purposes, I copied all the sql-ledger directory from AL8 to AL9, it worked.
AFAIK, the only important difference  between AL8 and AL9 is perl version (v5.26.3 vs v5.32.1, respectively).  Could it be because of lower perl version (v5.26.3) on AL8?  What is the min requirements for tekki 3.2.12.40?
Thank you.

**Comment by Tekki** [comment]
Take a look at the last entries in the Apache error and access logs. For an internal server error you should find the full error message there.
Can't tell you for sure what Perl version you need. 5.26 is from 2017, so it's not impossible that something breaks because of that.

**Comment by sse450** [comment]
No worries. Found the culprit. perl-open module was missing.

Sorry! Thank you.

**Comment by Tekki** [comment]
Please close this issue if the problem is solved.

**Comment by Tekki** [comment]
There is no change that I'm aware of. Does this password contain any non-ascii characters?

**Comment by sse450** [comment]
Thre is non-ascii characters. But, I normally use also symbols. But, for testing purposes, the newly created dataset uses just letters and numbers. Still no go.

**Comment by Tekki** [comment]
There in only Debian from me to the horizon, so until I have a AlmaLinux test server available I can't look in to these problems. Will create one in the next days.

**Comment by Tekki** [comment]
Just to be sure: this issue is only related to AlmaLinux 8?

**Comment by sse450** [comment]
Yes. Tekki 3.2.12.40 is working on AL9.

I don't know if it is meaningful. Actually, at the beginning, I had some similar authorization problems on AL9. I disabled  latex related options in sql-ledger.conf. Then, Tekki 3.2.12.40 on AL9 magically started authorization correctly.

**Comment by sse450** [comment]
I was able to pass authentication. DB owner was postgres. Created another user as owner of datasets. I did a lot of backup, sed commands on backups, restore etc. I am not sure if these helped.
Following login to tekki 3.2.12.40, database upgrade info comes up in the upper left corner ("Upgrading to Version 3.2.12 ... Continue"). When clicked "Continue" link, SL UI comes up. But, "Continue" does nothing on the datasets. It doesn't trigger DB upgrade process. Next time when I login, the same link comes up again.
No info on postgresql logs as well. Just to be sure I upgraded SL database user to superuser in PostgreSQL to avoid permission problems.
Any idea?

**Comment by Tekki** [comment]
The db upgrade issue should have been solved with the most recent version.
After you have made so many experiments, it is impossible to tell in what state your database is. If the start screen is shown without errors, you can for the moment set default variable `version2` manually with `INSERT INTO defaults (fldname, fldvalue) VALUES ('version2', '30');`. As soon as I have a test server for AlmaLinux, I can try everything with a clean installation and step for step.
The database user needs the permission to add and modify tables. If the Postgres configuration differs on the new system, you probably better use SQL-Ledger's own backup (I know, the restore is terribly slow).

**Comment by Tekki** [comment]
> I don't know if it is meaningful. Actually, at the beginning, I had some similar authorization problems on AL9. I disabled latex related options in sql-ledger.conf. Then, Tekki 3.2.12.40 on AL9 magically started authorization correctly.

As far as I know there is no magic in computers.
The LaTeX options don't influence the authorization. I rather suspect there was a typo in the file so it wasn't valid Perl.
You have to use `sql-ledger.conf.default` from version 40 and there change your settings. It has more variables than the one from DWS. And if you set the language, use one with '_utf'.

**Comment by sse450** [comment]
I transferred backup to my other server (AL9) and restored there. Tekki 3.2.12.40 successfully upgraded the DB. I again backup tekki version and restored it on AL8. Login not possible.
This issue is not related backup/restore process. There is something deeper.
Here is an experiment: I left all my dasasets aside. On AL8 installed fresh tekki 3.2.12.40. No any upgrade. Then,
1. Created a new dataset (tekki) using admin.pl.
2. I could successfully login that dataset.
3. I created another dataset using admin.pl with the very same password. Password is very simple.
It now looks like this:
![Screenshot from 2024-04-25 17-16-50](https://github.com/Tekki/sql-ledger/assets/15627450/b2ed075c-891b-4a79-9839-1b5594a5da3a)
There are 2 datasets, created using all SL (tekki) defaults with the same simple admin password. There is no any restore, just blank fresh table structure of tekki 3.2.12.40. Just to confirm, I see the tekki differences are in the database.

What should I expect? I should be able to login to both datasets, right? Wrong! Adding second set of dataset prevents any login at all. I cannot login to even the first dataset I created. Surely, this is beyond me. Something is missing/wrong on AL8 environment.
I tested tekki 3.2.12.40 on the other server (AL9). I can easily add, as many as datasets, easily.

**Comment by sse450** [comment]
This is what I did:

1. I rented a new VPS and installed fresh AL9 with all the components to run SL (apache 2.4.57, postgresql 15.6, perl v5.32.1, DBI, DBD-Pg etc).
2. Installed 3.2.12.40 tekki direct from github release.
3. Using admin.pl created a new dataset1 (no backup-restore).
4. I could login through login.pl.
5. Created another dataset2 (no backup-restore).
6. Login.pl gives me error "Incorrect Username or Password!".

If I delete entries for the dataset2 from "members" file, I can login dataset1 without any problem.

Another attempt:
1. Deleted all datasets.
2. Installed 3.2.12 DWS direct from sql-ledger.com.
3. Using admin.pl created a new dataset1 (no backup-restore).
4. I could login through login.pl.
5. Created another dataset2 (no backup-restore).
6. I could login through login.pl.

Dear Tekki, as you can see there is no backup-restore involved in these trials. The problem lies somewhere else.

PS. I use PostgreSQL 15.6 on all of the servers. But, I think, as there is no backup involved above, this is irrelevant at least for now.

Best wishes.

**Comment by sse450** [comment]
FINALLY, I found the problem.

If **$helpful_login = 0;** Then, the problem described above happens. First dataset works fine. But subsequent datasets gives "Incorrect Username or Password!" error on login.pl page.

If **$helpful_login = 1;** Then there is no problem at all. All logins work as intended.

Why is that? I don't know. We would be happy if Tekki chime in here.

I always overlooked "helpful_login" switch. Never thought, it would cause any problem. All my problems are gone now.

**Comment by Tekki** [comment]
> If **$helpful_login = 0;** Then, the problem described above happens.
> If **$helpful_login = 1;** Then, there is no problem at all.

For the moment I can't explain this. Can you tell me what language and charset you have set in `sql-ledger.conf` and what languages in the user accounts? And **IF THEY ARE JUST TEST DATA** the usernames and passwords that don't work?

**Comment by sse450** [comment]
in `sql-ledger.conf`
```
# set language and charset for login and admin
$language = "tr_utf";
$charset = "UTF8";
```
I tried also this:
```
# set language and charset for login and admin
$language = "";
$charset = "UTF8";
```
Both works.

User accounts are now set up as `Turkish (UTF-8)`. But, when the account was first created, it was `English`. Then changed to `Turkish (UTF-8)` in Preferences.

I created the admin accounts with a very simple password. Just "Dereboyu22". All chars are available in ASCII table. But, now, they are very complicated. It is now 20 character long with letters, numbers and symbols (I use Bitwarden). Still all letters are from ASCII. It is working like a charm.

I have a server, AL9 at office. I had these problems with that too. Always got ""Incorrect Username or Password!" error . Then, played with the switches in `sql-ledger.conf`. Changed some switches. Then, suddenly it started working.

Lately, I needed to install it on AL8/AL9 VPS. I couldn't. As frustrated, I wanted to compare the  `sql-ledger.conf` at the office with the `sql-ledger.conf` on VPS. I saw that the only difference was  $helpful_login. Changed to 1 like the one at the office. Bam! It started working.

Perhaps you can try this on a fresh linux.
1. Keep  $helpful_login as 0.
2. Create a default dataset with a simple password for admin. You will be able to login without any problem.
3. Create another dataset with the same password for admin.
4. Try to login. Normally, we expect SL to display two datasets as options. But, we cannot login due to "Incorrect Username or Password!" error.
5. If you change $helpful_login to 1, then you can login with the same user name (admin) and password.

For both databases, the user was "admin". It is default anyway. And the pass is "Dereboyu22". Nothing fancy.

**Comment by Tekki** [comment]
This means there are two admins with the same password? Now it gets clearer.

The idea of `$helpful_login = 0` is not to show a list of users, because this facilitates attacks to the system. If the option is activated, you have to use the complete and correct username. You don't login with `admin`, but with `admin@company1` or `admin@company2`.

By the way, the idea of using long passwords doesn't improve the security as long as we don't change the password encryption.  The `crypt` function only considers the first 8 characters of the password and discards the rest. This means from character 9 onward you can type whatever you want. We should change this as soon as possible.

**Comment by sse450** [comment]
Doh! Stupid me. ISo, it is a feature, not a bug!
Sorry for all the noise I created.
I am closing this issue.
Thank you.

**Comment by Tekki** [comment]
There must be a better explanation in `sql-ledger.conf.default`. Not yet completed for me.

**Comment by Tekki** [comment]
The next release will have better information in the config file, added through 12132c3.

@sse450 I recommend that you subscribe to new releases on this repo (releases only) so you get informed when a new version is published.
