### ISSUE TITLE
Cannot run wlprinter

### ISSUE THREAD

**Issue by sse450** [Tekki/sql-ledger#67]
When I run Batch--WLprinter, my browser (Firefox) always downloads wlprinter.jnlp. Doesn't run it.
Here is what I did:
1. My PC (Fedora 40,  10.10.1.44) and SL server (AL9, 10.10.1.16) have both java installed.
2. "`http://10.10.1.16`" is added to java security exemptions on my PC.
3. System--Workstations is filled as below.
![Screenshot from 2024-05-29 13-50-49](https://github.com/Tekki/sql-ledger/assets/15627450/be500571-2719-4641-a0c1-8ceed6db760a)
4. Copied `wlprinter.conf.default` to `wlprinter.conf` and modified as `$serveraddress = "http://10.10.1.16";`
5. Cups is running on my PC with an installed printer (Brother).

What am I doing wrong? Does Firefox need any plugin for `wlprinter` to work?

**Comment by sse450** [comment]
If I run `javaws ./wlprinter.jnlp` on my PC, I get error:
![Screenshot from 2024-05-29 17-36-45](https://github.com/Tekki/sql-ledger/assets/15627450/4da1d013-f74d-484f-9361-d01fc2f98fcc)
Details of the error:
![Screenshot from 2024-05-29 17-37-56](https://github.com/Tekki/sql-ledger/assets/15627450/08fd67e1-b242-4963-a4bb-c376edc290f3)
And this:
![Screenshot from 2024-05-29 17-38-14](https://github.com/Tekki/sql-ledger/assets/15627450/02f0f4d3-80da-4e63-a4cb-81dee2485380)
Error on the top is about security. But, I created an exemption for `http://10.10.1.16` as seen here: 
![Screenshot from 2024-05-29 17-46-47](https://github.com/Tekki/sql-ledger/assets/15627450/eead1224-20ec-437a-80fa-1dab7ec05970)
I think the exemption I created is not enough.

**Comment by Tekki** [comment]
WLprinter is not working anymore, we already have #49 for this. If there is anything to discuss, please use the other issue.
